
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
#   app:
#     build: .
#     depends_on:
#       - db
#     ports:
#       - "8080:8080"
#     environment:
#       DB_HOST: ${DB_HOST}
#       DB_PORT: 5432
#       DB_USER: ${DB_USER}
#       DB_PASSWORD: ${DB_PASS}
#       DB_NAME: ${DB_NAME}

# volumes:
#   pgdata:
