CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE IF NOT EXISTS users(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    password BYTEA NOT NULL,
    email CITEXT UNIQUE NOT NULL,
    age INT CHECK(age > 0 AND age < 100),
    gender BOOLEAN NOT NULL
);

